### ISSUE TITLE
Support import types from within typeDefs

### ISSUE THREAD

**Issue by katesclau** [neist/graphql-combine#2]
Use graphql-import to support `# import ...` on typeDefs resolving

**Comment by neist** [comment]
Hi!

What's your use-case? 😊

For example:

`posts.graphql`
```graphql
type Post {
  comments: [Comment]
  id: ID!
  text: String!
  tags: [String]
}
```
`comments.graphql`
```graphql
type Comment {
  id: ID!
  text: String!
}
```

This is taken from `graphql-import` and already works with `graphql-combine`, without the need for the import statement. It's possible to reference `Comment` in `posts.graphql` because they are part of one big type definition after being merged.
